version: "3"
services:
  ncc-wev-bot:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./data:/bot/data
      - ./src:/bot/src
    ports:
      - 127.0.0.1:3030:3030
    command: ["rye", "run", "streamlit", "run", "app.py", "--server.port=3030", "--server.baseUrlPath=/brecobot-counselor-chat", "--reload"]